FROM golang:latest

RUN mkdir -p /go/src/app
WORKDIR /go/src/app

# this will ideally be built by the ONBUILD below ;)
CMD ["go-wrapper", "run"]

ONBUILD COPY main.go /go/src/app
ONBUILD RUN go-wrapper download
ONBUILD RUN go-wrapper install